"""
Django settings for authProject project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

#Funcion que permite sacar instervalos de tiempo
# Ej: A partir del momento actual calcule una fecha 5 minutos adelante
from datetime import timedelta 


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q=wz0&5$qn1ayypn-hy@i$2#o+*0f!rj-3f^awrnhxstu3^89q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'authApp',
]
# configuracion de como se deben generar los token cuando se este haciendo la autenticacion
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME'   : timedelta(minutes=5), # Tiempo de vida del token de acceso
    'REFRESH_TOKEN_LIFETIME'  : timedelta(days=1),    # Tiempo de vida del Refresh token
    'ROTATE_REFRESH_TOKENS'   : False,      # Rotacion de los token refresh
    'BLACKLIST_AFTER_ROTATION': True,       # que despues de que se hagan el refresh ese token no se vuelva a usar
    'UPDATE_LAST_LOGIN'       : False,
    'ALGORITHM'               : 'HS256',    # Se define el algoritmo de encriptacion de los token
    'USER_ID_FIELD'           : 'id',
    'USER_ID_CLAIM'           : 'user_id',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Para que Django Rest-Framework pueda trabajar, le estamos dando permisos 
# y estamos verificando como se va a hacer autenticacion 
REST_FRAMEWORK = {
    # Permiso de Acceso 
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',# se da control total sobre las clases
    ),
    # Autenticacion de Acceso a esas Clases
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',# Mecanismo de Autenticacion por defecto
    )
}

AUTH_USER_MODEL = 'authApp.User'

ROOT_URLCONF = 'authProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'authProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2', # conector de python a posgress
        'NAME': 'dcsvrcq6rsfnv5',
        'USER': 'grzuqueoqbvemn',
        'PASSWORD': 'd931e5695750847457c2654eef54ac26fb1e46c10fe031af2b751e8c9f40fc38',
        'HOST': 'ec2-34-233-105-94.compute-1.amazonaws.com',
        'PORT': '5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import django_heroku
django_heroku.settings(locals())
